---
# The AWS S3 ansible role is deliberately not used, as it does not handle multipart uploads well.
# See https://github.com/ansible/ansible/issues/5442
#
# This expects to authenticat based on the invokers AWS credentials, supplied through environment variables
- name: "Download Magento release"
  shell: |
      AWS_ACCESS_KEY_ID="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}" \
      AWS_SECRET_ACCESS_KEY="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}" \
      aws s3 cp s3://{{ magento_bucket_name }}/{{ magento_storage_file_path }} {{ magento_workdir }} \
        --cli-read-timeout 300 \
        --cli-connect-timeout 0
  args:
    creates: "{{ magento_workdir }}/{{ magento_storage_file_name }}"
  when:
    - not magento_release_stat.stat.exists
    - magento_skip_release == False
