---
- name: "Discover old clone/release directories which need to be cleaned"
  find:
    paths: "{{ magento_release_folder }}"
    age: "{{ magento_clones_cleanup_min_age }}"
    file_type: directory
    age_stamp: "ctime"
  register: magento_clones_for_cleanup

- name: "Remove old clones/releases"
  file:
    path: "{{ item.path }}"
    state: absent
  when: magento_cleanup_old_clones == True
  with_items: "{{ (magento_clones_for_cleanup.files | sort(attribute='ctime', reverse=True))[magento_clones_to_keep:] | list }}"
