---
- name: "Discover old clone/release directories which need to be cleaned"
  find:
    paths: "{{ magento_release_folder }}"
    age: "{{ magento_clones_cleanup_min_age }}"
    file_type: directory
    age_stamp: "ctime"
  register: magento_clones_for_cleanup

- name: "Remove old clones/releases asynchronously"
  file:
    path: "{{ item.path }}"
    state: absent
  when: magento_cleanup_old_clones and magento_allow_async_cleanup_old_clones
  with_items: "{{ (magento_clones_for_cleanup.files | sort(attribute='ctime', reverse=True))[magento_clones_to_keep:] | list }}"
  async: 600
  poll: 0

- name: "Remove old clones/releases synchronously"
  file:
    path: "{{ item.path }}"
    state: absent
  when: magento_cleanup_old_clones and (not magento_allow_async_cleanup_old_clones)
  with_items: "{{ (magento_clones_for_cleanup.files | sort(attribute='ctime', reverse=True))[magento_clones_to_keep:] | list }}"